### ISSUE TITLE
客户端完全编译不了

### ISSUE THREAD

**Issue by yufeixuan** [entboost/ebc#1]
客户端完全编译不了

**Comment by entboost** [comment]
可以编译的，编译步骤如下：
1 编译 mycp/proj/MSVC9.0/MYCPBase.sln 解决方案里面的 CGCClass, CGCLib 二个工程；
2 然后依顺序编译 proj/MSVC9.0/entboost.sln 解决方案里面的 libebcm,libebrd, libebum, eblogin, ebc 即可；
3 其他工程不需要编译；
